language: ruby

sudo: false
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0

script: bundle exec rspec

gemfile:
  - gemfiles/Gemfile-rspec-3.4.x
  - gemfiles/Gemfile-rspec-3.5.x

